#include "php_capstone.h"

#define REGISTER_CAPSTONE_CONSTANT(__c) REGISTER_LONG_CONSTANT(#__c, __c, CONST_CS | CONST_PERSISTENT)

void php_capstone_register_constants(int module_number)
{
// {{{ cs_arch
REGISTER_CAPSTONE_CONSTANT(CS_ARCH_ARM);
REGISTER_CAPSTONE_CONSTANT(CS_ARCH_ARM64);
REGISTER_CAPSTONE_CONSTANT(CS_ARCH_MIPS);
REGISTER_CAPSTONE_CONSTANT(CS_ARCH_X86);
REGISTER_CAPSTONE_CONSTANT(CS_ARCH_PPC);
REGISTER_CAPSTONE_CONSTANT(CS_ARCH_SPARC);
REGISTER_CAPSTONE_CONSTANT(CS_ARCH_SYSZ);
REGISTER_CAPSTONE_CONSTANT(CS_ARCH_XCORE);
REGISTER_CAPSTONE_CONSTANT(CS_ARCH_MAX);
REGISTER_CAPSTONE_CONSTANT(CS_ARCH_ALL);
// }}} cs_arch

// {{{ cs_mode
REGISTER_CAPSTONE_CONSTANT(CS_MODE_LITTLE_ENDIAN);
REGISTER_CAPSTONE_CONSTANT(CS_MODE_ARM);
REGISTER_CAPSTONE_CONSTANT(CS_MODE_16);
REGISTER_CAPSTONE_CONSTANT(CS_MODE_32);
REGISTER_CAPSTONE_CONSTANT(CS_MODE_64);
REGISTER_CAPSTONE_CONSTANT(CS_MODE_THUMB);
REGISTER_CAPSTONE_CONSTANT(CS_MODE_MCLASS);
REGISTER_CAPSTONE_CONSTANT(CS_MODE_V8);
REGISTER_CAPSTONE_CONSTANT(CS_MODE_MICRO);
REGISTER_CAPSTONE_CONSTANT(CS_MODE_MIPS3);
REGISTER_CAPSTONE_CONSTANT(CS_MODE_MIPS32R6);
REGISTER_CAPSTONE_CONSTANT(CS_MODE_MIPSGP64);
REGISTER_CAPSTONE_CONSTANT(CS_MODE_V9);
REGISTER_CAPSTONE_CONSTANT(CS_MODE_BIG_ENDIAN);
REGISTER_CAPSTONE_CONSTANT(CS_MODE_MIPS32);
REGISTER_CAPSTONE_CONSTANT(CS_MODE_MIPS64);
// }}} cs_mode

// {{{ cs_opt_type
REGISTER_CAPSTONE_CONSTANT(CS_OPT_INVALID);
REGISTER_CAPSTONE_CONSTANT(CS_OPT_SYNTAX);
REGISTER_CAPSTONE_CONSTANT(CS_OPT_DETAIL);
REGISTER_CAPSTONE_CONSTANT(CS_OPT_MODE);
REGISTER_CAPSTONE_CONSTANT(CS_OPT_MEM);
REGISTER_CAPSTONE_CONSTANT(CS_OPT_SKIPDATA);
REGISTER_CAPSTONE_CONSTANT(CS_OPT_SKIPDATA_SETUP);
// }}} cs_opt_type

// {{{ cs_opt_value
REGISTER_CAPSTONE_CONSTANT(CS_OPT_OFF);
REGISTER_CAPSTONE_CONSTANT(CS_OPT_ON);
REGISTER_CAPSTONE_CONSTANT(CS_OPT_SYNTAX_DEFAULT);
REGISTER_CAPSTONE_CONSTANT(CS_OPT_SYNTAX_INTEL);
REGISTER_CAPSTONE_CONSTANT(CS_OPT_SYNTAX_ATT);
REGISTER_CAPSTONE_CONSTANT(CS_OPT_SYNTAX_NOREGNAME);
// }}} cs_opt_value

// {{{ cs_op_type
REGISTER_CAPSTONE_CONSTANT(CS_OP_INVALID);
REGISTER_CAPSTONE_CONSTANT(CS_OP_REG);
REGISTER_CAPSTONE_CONSTANT(CS_OP_IMM);
REGISTER_CAPSTONE_CONSTANT(CS_OP_MEM);
REGISTER_CAPSTONE_CONSTANT(CS_OP_FP);
// }}} cs_op_type

// {{{ cs_group_type
REGISTER_CAPSTONE_CONSTANT(CS_GRP_INVALID);
REGISTER_CAPSTONE_CONSTANT(CS_GRP_JUMP);
REGISTER_CAPSTONE_CONSTANT(CS_GRP_CALL);
REGISTER_CAPSTONE_CONSTANT(CS_GRP_RET);
REGISTER_CAPSTONE_CONSTANT(CS_GRP_INT);
REGISTER_CAPSTONE_CONSTANT(CS_GRP_IRET);
// }}} cs_group_type

// {{{ cs_err
REGISTER_CAPSTONE_CONSTANT(CS_ERR_OK);
REGISTER_CAPSTONE_CONSTANT(CS_ERR_MEM);
REGISTER_CAPSTONE_CONSTANT(CS_ERR_ARCH);
REGISTER_CAPSTONE_CONSTANT(CS_ERR_HANDLE);
REGISTER_CAPSTONE_CONSTANT(CS_ERR_CSH);
REGISTER_CAPSTONE_CONSTANT(CS_ERR_MODE);
REGISTER_CAPSTONE_CONSTANT(CS_ERR_OPTION);
REGISTER_CAPSTONE_CONSTANT(CS_ERR_DETAIL);
REGISTER_CAPSTONE_CONSTANT(CS_ERR_MEMSETUP);
REGISTER_CAPSTONE_CONSTANT(CS_ERR_VERSION);
REGISTER_CAPSTONE_CONSTANT(CS_ERR_DIET);
REGISTER_CAPSTONE_CONSTANT(CS_ERR_SKIPDATA);
REGISTER_CAPSTONE_CONSTANT(CS_ERR_X86_ATT);
REGISTER_CAPSTONE_CONSTANT(CS_ERR_X86_INTEL);
// }}} cs_err

}